/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package v1alpha1

import (
	v1alpha1 "github.com/simonferquel/devoxx-2018-k8s-workshop/pkg/apis/etcdaas/v1alpha1"
	scheme "github.com/simonferquel/devoxx-2018-k8s-workshop/pkg/client/clientset/versioned/scheme"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	rest "k8s.io/client-go/rest"
)

// ETCDInstancesGetter has a method to return a ETCDInstanceInterface.
// A group's client should implement this interface.
type ETCDInstancesGetter interface {
	ETCDInstances(namespace string) ETCDInstanceInterface
}

// ETCDInstanceInterface has methods to work with ETCDInstance resources.
type ETCDInstanceInterface interface {
	Create(*v1alpha1.ETCDInstance) (*v1alpha1.ETCDInstance, error)
	Update(*v1alpha1.ETCDInstance) (*v1alpha1.ETCDInstance, error)
	UpdateStatus(*v1alpha1.ETCDInstance) (*v1alpha1.ETCDInstance, error)
	Delete(name string, options *v1.DeleteOptions) error
	DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error
	Get(name string, options v1.GetOptions) (*v1alpha1.ETCDInstance, error)
	List(opts v1.ListOptions) (*v1alpha1.ETCDInstanceList, error)
	Watch(opts v1.ListOptions) (watch.Interface, error)
	Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1alpha1.ETCDInstance, err error)
	ETCDInstanceExpansion
}

// eTCDInstances implements ETCDInstanceInterface
type eTCDInstances struct {
	client rest.Interface
	ns     string
}

// newETCDInstances returns a ETCDInstances
func newETCDInstances(c *EtcdaasV1alpha1Client, namespace string) *eTCDInstances {
	return &eTCDInstances{
		client: c.RESTClient(),
		ns:     namespace,
	}
}

// Get takes name of the eTCDInstance, and returns the corresponding eTCDInstance object, and an error if there is any.
func (c *eTCDInstances) Get(name string, options v1.GetOptions) (result *v1alpha1.ETCDInstance, err error) {
	result = &v1alpha1.ETCDInstance{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("etcdinstances").
		Name(name).
		VersionedParams(&options, scheme.ParameterCodec).
		Do().
		Into(result)
	return
}

// List takes label and field selectors, and returns the list of ETCDInstances that match those selectors.
func (c *eTCDInstances) List(opts v1.ListOptions) (result *v1alpha1.ETCDInstanceList, err error) {
	result = &v1alpha1.ETCDInstanceList{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("etcdinstances").
		VersionedParams(&opts, scheme.ParameterCodec).
		Do().
		Into(result)
	return
}

// Watch returns a watch.Interface that watches the requested eTCDInstances.
func (c *eTCDInstances) Watch(opts v1.ListOptions) (watch.Interface, error) {
	opts.Watch = true
	return c.client.Get().
		Namespace(c.ns).
		Resource("etcdinstances").
		VersionedParams(&opts, scheme.ParameterCodec).
		Watch()
}

// Create takes the representation of a eTCDInstance and creates it.  Returns the server's representation of the eTCDInstance, and an error, if there is any.
func (c *eTCDInstances) Create(eTCDInstance *v1alpha1.ETCDInstance) (result *v1alpha1.ETCDInstance, err error) {
	result = &v1alpha1.ETCDInstance{}
	err = c.client.Post().
		Namespace(c.ns).
		Resource("etcdinstances").
		Body(eTCDInstance).
		Do().
		Into(result)
	return
}

// Update takes the representation of a eTCDInstance and updates it. Returns the server's representation of the eTCDInstance, and an error, if there is any.
func (c *eTCDInstances) Update(eTCDInstance *v1alpha1.ETCDInstance) (result *v1alpha1.ETCDInstance, err error) {
	result = &v1alpha1.ETCDInstance{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("etcdinstances").
		Name(eTCDInstance.Name).
		Body(eTCDInstance).
		Do().
		Into(result)
	return
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().

func (c *eTCDInstances) UpdateStatus(eTCDInstance *v1alpha1.ETCDInstance) (result *v1alpha1.ETCDInstance, err error) {
	result = &v1alpha1.ETCDInstance{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("etcdinstances").
		Name(eTCDInstance.Name).
		SubResource("status").
		Body(eTCDInstance).
		Do().
		Into(result)
	return
}

// Delete takes name of the eTCDInstance and deletes it. Returns an error if one occurs.
func (c *eTCDInstances) Delete(name string, options *v1.DeleteOptions) error {
	return c.client.Delete().
		Namespace(c.ns).
		Resource("etcdinstances").
		Name(name).
		Body(options).
		Do().
		Error()
}

// DeleteCollection deletes a collection of objects.
func (c *eTCDInstances) DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error {
	return c.client.Delete().
		Namespace(c.ns).
		Resource("etcdinstances").
		VersionedParams(&listOptions, scheme.ParameterCodec).
		Body(options).
		Do().
		Error()
}

// Patch applies the patch and returns the patched eTCDInstance.
func (c *eTCDInstances) Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1alpha1.ETCDInstance, err error) {
	result = &v1alpha1.ETCDInstance{}
	err = c.client.Patch(pt).
		Namespace(c.ns).
		Resource("etcdinstances").
		SubResource(subresources...).
		Name(name).
		Body(data).
		Do().
		Into(result)
	return
}
