/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by informer-gen. DO NOT EDIT.

package v1alpha1

import (
	time "time"

	etcdaas_v1alpha1 "github.com/simonferquel/devoxx-2018-k8s-workshop/pkg/apis/etcdaas/v1alpha1"
	versioned "github.com/simonferquel/devoxx-2018-k8s-workshop/pkg/client/clientset/versioned"
	internalinterfaces "github.com/simonferquel/devoxx-2018-k8s-workshop/pkg/client/informers/externalversions/internalinterfaces"
	v1alpha1 "github.com/simonferquel/devoxx-2018-k8s-workshop/pkg/client/listers/etcdaas/v1alpha1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
	watch "k8s.io/apimachinery/pkg/watch"
	cache "k8s.io/client-go/tools/cache"
)

// ETCDInstanceInformer provides access to a shared informer and lister for
// ETCDInstances.
type ETCDInstanceInformer interface {
	Informer() cache.SharedIndexInformer
	Lister() v1alpha1.ETCDInstanceLister
}

type eTCDInstanceInformer struct {
	factory          internalinterfaces.SharedInformerFactory
	tweakListOptions internalinterfaces.TweakListOptionsFunc
	namespace        string
}

// NewETCDInstanceInformer constructs a new informer for ETCDInstance type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewETCDInstanceInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers) cache.SharedIndexInformer {
	return NewFilteredETCDInstanceInformer(client, namespace, resyncPeriod, indexers, nil)
}

// NewFilteredETCDInstanceInformer constructs a new informer for ETCDInstance type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewFilteredETCDInstanceInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers, tweakListOptions internalinterfaces.TweakListOptionsFunc) cache.SharedIndexInformer {
	return cache.NewSharedIndexInformer(
		&cache.ListWatch{
			ListFunc: func(options v1.ListOptions) (runtime.Object, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.EtcdaasV1alpha1().ETCDInstances(namespace).List(options)
			},
			WatchFunc: func(options v1.ListOptions) (watch.Interface, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.EtcdaasV1alpha1().ETCDInstances(namespace).Watch(options)
			},
		},
		&etcdaas_v1alpha1.ETCDInstance{},
		resyncPeriod,
		indexers,
	)
}

func (f *eTCDInstanceInformer) defaultInformer(client versioned.Interface, resyncPeriod time.Duration) cache.SharedIndexInformer {
	return NewFilteredETCDInstanceInformer(client, f.namespace, resyncPeriod, cache.Indexers{cache.NamespaceIndex: cache.MetaNamespaceIndexFunc}, f.tweakListOptions)
}

func (f *eTCDInstanceInformer) Informer() cache.SharedIndexInformer {
	return f.factory.InformerFor(&etcdaas_v1alpha1.ETCDInstance{}, f.defaultInformer)
}

func (f *eTCDInstanceInformer) Lister() v1alpha1.ETCDInstanceLister {
	return v1alpha1.NewETCDInstanceLister(f.Informer().GetIndexer())
}
